[[connectors]]
id = "kafka_sink"
type = "kafka"
allow_override = ["brokers", "topic", "config", "num_partitions", "replication"]

[connectors.params]
brokers = "localhost:9092"
topic = "vaultwarden"
num_partitions = 1
replication = 1
config = []
