version = "2.0"

[sink_group]
name = "/sink/nginx/vlogs"
oml = ["/oml/normal/nginx_access"]

[[sink_group.sinks]]
name = "nginx_victorialogs"
connect = "victorialogs_sink"

[sink_group.sinks.params]
endpoint = "http://localhost:9428"
insert_path = "/insert/jsonline"
create_time_field = "occur_time"
