version = "2.0"

[sink_group]
name = "/sink/vaultwarden/kafka"
oml = ["/oml/normal/vaultwarden_request"]

[[sink_group.sinks]]
name = "vaultwarden_kafka"
connect = "kafka_sink"

[sink_group.sinks.params]
brokers = "localhost:9092"
topic = "vaultwarden"
