[[connectors]]
id = "vlogs_sink"
type = "victorialogs"
allow_override = ["endpoint", "insert_path", "batch_size"]

[connectors.params]
endpoint = "http://localhost:9428"
insert_path = "/api/_bulk"
flush_interval_secs = 2
batch_size = 1024
